name: core_app
version: 1.4.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  mfa_authentication:
    path: "../mfa_authentication"
  mfa_home:
    path: "../mfa_home"
  mfa_profile:
    path: "../mfa_profile"
  common_dependencies:
    path: "../common_dependencies"
  common_utils:
    path: "../common_utils"
  provider: ^6.0.5

dev_dependencies:
  git_hooks: ^1.0.0
  dart_pre_commit: ^4.1.0
  pub_release: ^8.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/muhna_logo.jpg

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets\fonts\Source_Sans_Pro\SourceSansPro-SemiBold.ttf
        - asset: assets\fonts\Source_Sans_Pro\SourceSansPro-Regular.ttf

scripts:
  pub_release: pub_release
