name: Build and Release

on:
  push:
    branches:
      - "main"

jobs:
  # build_android_apk:
  #   name: Build Flutter (Android)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - uses: actions/cache@v2
  #       id: cache-dependencies
  #       with:
  #         path: ~/.pub-cache
  #         key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pub-cache-
  #     - run: flutter pub get
  #       if: steps.cache-dependencies.outputs.cache-hit != 'true'
  #     - run: flutter clean
  #     - run: flutter build apk
  #     - name: Upload APK
  #       uses: actions/upload-artifact@v2.1.4
  #       with:
  #         name: apk
  #         path: build/app/outputs/flutter-apk/app-release.apk

  semantic_release:
    name: Run semantic release
    # needs: build_android_apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Semantic Release and dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Update PubSpec
        run : npm run updateVersion
    permissions:
      contents: write

  # release:
  #   name: Release
  #   needs: build_android_apk
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     EDITOR: nano
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Set up Dart
  #       uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - uses: actions/cache@v2
  #       id: cache-dependencies
  #       with:
  #         path: ~/.pub-cache
  #         key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pub-cache-
  #     - name: Install dependencies
  #       run: flutter pub get
  #     - name: Set up Git user
  #       run: |
  #         git config user.name "${GITHUB_ACTOR}"
  #         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
  #     - name: Run pub_release
  #       run: flutter pub run pub_release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
